name: Main
on:
  pull_request:
  push:
    branches: [master, next]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        bun-version: [1.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: bun i

      - name: Get changed files from evmcrispr
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: "packages/evmcrispr/{src,test}/**"

      - name: Build
        run: bun run build

      - name: Check evmcrispr types
        run: bun check

      - name: Tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "ARCHIVE_NODE_ENDPOINT=${{ secrets.ARCHIVE_NODE_ENDPOINT }}" >> packages/evmcrispr/.env
          echo "VITE_PINATA_JWT=${{ secrets.VITE_PINATA_JWT }}" >> packages/evmcrispr/.env
          echo "ETHERSCAN_API=${{ secrets.ETHERSCAN_API }}" >> packages/evmcrispr/.env
          bun test:coverage
        env:
          ARCHIVE_NODE_ENDPOINT: ${{ secrets.ARCHIVE_NODE_ENDPOINT }}
          VITE_PINATA_JWT: ${{ secrets.VITE_PINATA_JWT }}
          ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node-version }}
          base-path: "packages/evmcrispr"
          path-to-lcov: "packages/evmcrispr/coverage/lcov.info"
