name: Main
on:
  pull_request:
  push:
    branches: [master, next]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [7.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm i

      - name: Get changed files from evmcrispr
        id: changed-files
        uses: tj-actions/changed-files@v20
        with:
          files: 'packages/evmcrispr/src/**'

      - name: Link Dependencies
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: pnpm dev

      - name: Lint code
        run: pnpm lint

      - name: Check evmcrispr types
        run: pnpm lint:evmcrispr:types

      - name: Build
        run: pnpm build

      - name: Check size
        run: pnpm size
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_BRANCH_BASE: master

      - name: Tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pnpm test:coverage
        env:
          ARCHIVE_NODE_ENDPOINT: ${{ secrets.ARCHIVE_NODE_ENDPOINT }}
          VITE_PINATA_JWT: ${{ secrets.VITE_PINATA_JWT }}
          ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node-version }}
          base-path: 'packages/evmcrispr'
          path-to-lcov: 'packages/evmcrispr/coverage/lcov.info'
