name: Docs
on:
  push:
    branches:
      - main
    paths:
      - src/index.ts
      - src/EVMcrispr.ts
      - src/errors.ts
      - src/types.ts
      - README.md
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        pnpm-version: [6.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          pnpm config set unsafe-perm true
          pnpm i
          pnpm generate-typedocs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
