name: Release

on:
  push:
    branches: [master]
    paths:
      - "packages/evmcrispr/**"

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "bun"
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: bun i

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          version: bun changeset:version
          publish: bun changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
